[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.1.2"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
fancy-regex = "0.12.0"
lazy_static = "1.4.0"

[dev-dependencies]
rstest = "0.18.2"
unindent = "0.2.3"
